[package]
name = "timeseries"
version = "0.1.0"
authors = ["thomas9911 <thomastimmer11@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.chrono]
version = "*"
optional = true
[dependencies.ndarray]
version = "*"
optional = true
[dependencies.csv]
version = "*"
optional = true
[dependencies.serde]
version = "^1"
features = ["derive"]
optional = true

[dev-dependencies]
serde_json = "^1"

[[example]]
name = "data"
required-features = ["csv", "chrono"]

[[example]]
name = "array"
required-features = ["chrono"]
